// Game state constants
export const GAME_STATES = {
    P1_DRAWING: 'P1_DRAWING',
    P2_WAITING: 'P2_WAITING',
    P2_DRAWING: 'P2_DRAWING',
    CAR_ANIMATING: 'CAR_ANIMATING',
    SHOWING_SCORE: 'SHOWING_SCORE'
};

// Visual constants
export const VISUAL_CONSTANTS = {
    P1_COLOR: 'lightblue',
    P1_WIDTH: 40,
    P2_COLOR: 'black',
    P2_WIDTH: 3,
    START_COLOR: 'gray',
    END_COLOR: 'green',
    MARKER_RADIUS_FACTOR: 1.4,
    HIT_THRESHOLD_FACTOR: 1.1,
    START_END_SNAP_RADIUS_FACTOR: 1.5
};

// Gameplay constants
export const GAMEPLAY_CONSTANTS = {
    PROGRESS_INTERVAL: 0.10,
    SCORE_THRESHOLD: 20,
    SCORE_POINTS: 100,
    MAX_PATH_LENGTH_FACTOR: 1.20
};

// Car constants
export const CAR_CONSTANTS = {
    PIXEL_SPEED: 2,
    ANIMATION_INTERVAL: 16,
    SMOOTHING_WINDOW: 10,
    CURVATURE_WINDOW: 10,
    MAX_CURVATURE: 0.9,
    ACCELERATION_RATE: 0.005,
    BASE_DECELERATION_RATE: 0.8,
    CURVE_LOOK_AHEAD: 0.15,
    MAX_DECELERATION_RATE: 1.2,
    CURVE_PREPARATION_DISTANCE: 0.1,
    FINISH_PREPARATION_DISTANCE: 0.2,
    MIN_FINISH_SPEED: 0.3,
    WHEEL_TURN_SPEED: 0.15,
    MAX_WHEEL_ANGLE: Math.PI / 4,
    WHEELBASE: 20,
    SKID_TURN_RATE_MULTIPLIER: 0.15
};

// UI constants
export const UI_CONSTANTS = {
    THUMBNAIL_WIDTH: 240,
    THUMBNAIL_HEIGHT: 150,
    THUMBNAIL_PADDING: 10
};
